// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsbHtNssryG8kj9M4nvxINK8q1QjgUyRk',
    appId: '1:185200745886:web:949d451599577992818a8f',
    messagingSenderId: '185200745886',
    projectId: 'ecommerce-app-3a055',
    authDomain: 'ecommerce-app-3a055.firebaseapp.com',
    storageBucket: 'ecommerce-app-3a055.firebasestorage.app',
    measurementId: 'G-5BH5D9RVLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX5eq-hP9Bjvh-flAitEPnDTjkhfo-dNA',
    appId: '1:185200745886:android:38f9730b481a1727818a8f',
    messagingSenderId: '185200745886',
    projectId: 'ecommerce-app-3a055',
    storageBucket: 'ecommerce-app-3a055.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU7maqE7udgFJpnR0CxIT7Kg1l3puNWfs',
    appId: '1:185200745886:ios:0b6b6fdf4e8e9584818a8f',
    messagingSenderId: '185200745886',
    projectId: 'ecommerce-app-3a055',
    storageBucket: 'ecommerce-app-3a055.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU7maqE7udgFJpnR0CxIT7Kg1l3puNWfs',
    appId: '1:185200745886:ios:0b6b6fdf4e8e9584818a8f',
    messagingSenderId: '185200745886',
    projectId: 'ecommerce-app-3a055',
    storageBucket: 'ecommerce-app-3a055.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsbHtNssryG8kj9M4nvxINK8q1QjgUyRk',
    appId: '1:185200745886:web:047bdae9b49057ee818a8f',
    messagingSenderId: '185200745886',
    projectId: 'ecommerce-app-3a055',
    authDomain: 'ecommerce-app-3a055.firebaseapp.com',
    storageBucket: 'ecommerce-app-3a055.firebasestorage.app',
    measurementId: 'G-ELD6MR8V5N',
  );
}
